Fixing issues #141
RoboCup-SPL/Rules pull request #144
Opened 2024-01-29 00:56 UTC by ben47955

Fixing issues #141

2024-02-12 20:06 UTC, ben47955 commented
Ready for review.  I kinda have a doubt for the need of a coma somewhere though.

2024-02-20 07:45 UTC, arnemoos requested changes

2024-02-20 07:45 UTC, arnemoos commented on rules/forbidden_actions.tex
> + will be penalized \textit{in place} on the field until the penalty is over for \qty{15}{\second} in the \textit{playing} state.
That you are penalized "until the penalty is over" should be clear and does not resolve the issue. 
However, I would leave the sentence as before and add a note like: 

It's important to note that the penalty duration only counts down during the playing state.

2024-02-20 07:47 UTC, arnemoos commented on rules/forbidden_actions.tex
>  Robots that begin moving their legs or locomote in any fashion before the specified state in the subsections
before reaching the specified state in the subsections

2024-03-15 10:43 UTC, arnemoos approved these changes

2024-03-15 12:17 UTC, merged