Adds 7vs7 robot usage and misusage
RoboCup-SPL/Rules pull request #49
Opened 2022-05-11 07:43 UTC by PatrickGoettsch

2022-05-11 08:57 UTC, arnemoos requested changes

2022-05-11 08:57 UTC, arnemoos commented on content/technical_challenges.tex
> +                All teams an encouraged to implement features in their code to prevent falling or when falling to fall less destructive. We ask all teams to exchange ideas on that in our \textit{RC-S
All teams **are** encouraged

2022-05-11 08:57 UTC, arnemoos commented on content/technical_challenges.tex
> +            All teams using robots for the robot pool are encouraged to implement robot protection features to prevent abnormal damages and abnormal probability of a fall robot. The teams providing r
of a fall**en** robot.

2022-05-12 06:20 UTC, PatrickGoettsch commented on content/technical_challenges.tex
> +                All teams an encouraged to implement features in their code to prevent falling or when falling to fall less destructive. We ask all teams to exchange ideas on that in our \textit{RC-S
Done

2022-05-12 06:26 UTC, PatrickGoettsch commented on content/technical_challenges.tex
> +            All teams using robots for the robot pool are encouraged to implement robot protection features to prevent abnormal damages and abnormal probability of a fall robot. The teams providing r
Done

2022-05-12 06:26 UTC, merged