Adjust tournment system description
RoboCup-SPL/Rules pull request #50
Opened 2022-05-11 08:07 UTC by PatrickGoettsch

2022-05-11 09:01 UTC, arnemoos requested changes

2022-05-11 21:54 UTC, sseering commented
Looks good to me in combination with Arnes changes.

2022-05-12 06:15 UTC, PatrickGoettsch commented on content/app_competition_rules.tex
> +  \item Initial rank ranking of participating teams
Done

2022-05-12 06:15 UTC, PatrickGoettsch commented on content/app_competition_rules.tex
> +  \item Competition mode with which rules will be applied
Done

2022-05-12 06:17 UTC, merged