75-data-minimization-challenge
RoboCup-SPL/Rules pull request #96
Opened 2023-01-13 19:01 UTC by EmanueleMusumeci

2023-01-16 13:15 UTC, PatrickGoettsch requested changes

2023-01-16 13:15 UTC, PatrickGoettsch commented on challenges/data_minimization_challenge.tex
> +Being an in-game challenge, all teams participating in the main competition will automatically take part in this challenge if they score at least one goal during the whole duration of the preliminary
```suggestion
Being an in-game challenge, all teams participating in the main competition will automatically take part in this challenge if they score at least one goal during the whole duration of the preliminary tournament phase.
```

2023-01-16 15:53 UTC, EmanueleMusumeci commented on challenges/data_minimization_challenge.tex
> +Being an in-game challenge, all teams participating in the main competition will automatically take part in this challenge if they score at least one goal during the whole duration of the preliminary
I agree, my mistake :)

2023-01-16 15:53 UTC, EmanueleMusumeci commented on challenges/data_minimization_challenge.tex
> +The final objective of each team is to minimize the $A^t$ average.
Thanks :)

2023-01-16 15:54 UTC, EmanueleMusumeci commented on challenges/data_minimization_challenge.tex
> +An average is computed for each match while the final score $A^\text{t}$ for team $t$ will simply be the global average over all matches disputed by that team:
With global average I just meant the average over all matches but I think your edit makes it more readable :)

2023-01-16 16:03 UTC, EmanueleMusumeci commented on challenges/data_minimization_challenge.tex
> +This challenge will take place throughout regular games and the score will be based on the quantity of bytes exchanged by active robots during matches.
I agree with this point. I don't think a discussion about it is needed in the next TC meeting and we might implement it right away but if a discussion is needed I'm open to this possibility. I'm applying your suggestion.

2023-01-16 16:03 UTC, EmanueleMusumeci commented on challenges/data_minimization_challenge.tex
> +Network data usage will be evaluated by keeping track of the ratio $R$ between the cumulative count of bytes sent by all active robots in the team and the total uptime of robots in the team for SPL m
Thank you, I've spent some words to define this, could you give a look at line 18?

2023-01-17 09:42 UTC, PatrickGoettsch commented on challenges/data_minimization_challenge.tex
> +    \item $t_i$ is the uptime of robot $i$, defined as the time during which robot $i$ is playing and is not penalized.
I would phrase it a little bit differently:
```suggestion
    \item $t_i$ is the uptime of robot $i$, i.e., the duration robot $i$ is participating in the match and is not penalized.
```

2023-01-18 22:11 UTC, merged